package com.gc.system.entity;

// Generated 2016-6-15 15:37:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * HotsalesGoods generated by hbm2java
 */
@Entity
@Table(name = "hotsales_goods")
public class HotsalesGoods implements java.io.Serializable {

	private static final long serialVersionUID = -5168536684086612109L;
	private Integer id;
	private String productName;
	private String specifications;
	private String material;
	private String origin;
	private String area;
	private Double num;
	private String wearhouse;
	private String company;
	private Double price;
	private String description;
	private Date effectiveDate;

	private Double priceEnd;// 检索条件，非映射字段
	private String effectiveDateStr;//检索key
	
	
	public HotsalesGoods() {
	}

	public HotsalesGoods(String productName, String company) {
		this.productName = productName;
		this.company = company;
	}

	public HotsalesGoods(String productName, String specifications,
			String material, String origin, String area, Double num,
			String wearhouse, String company, Double price, String description,
			Date effectiveDate) {
		this.productName = productName;
		this.specifications = specifications;
		this.material = material;
		this.origin = origin;
		this.area = area;
		this.num = num;
		this.wearhouse = wearhouse;
		this.company = company;
		this.price = price;
		this.description = description;
		this.effectiveDate = effectiveDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "product_name", nullable = false, length = 200)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "specifications", length = 200)
	public String getSpecifications() {
		return this.specifications;
	}

	public void setSpecifications(String specifications) {
		this.specifications = specifications;
	}

	@Column(name = "material", length = 200)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "origin", length = 200)
	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	@Column(name = "area", length = 200)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "num", precision = 11)
	public Double getNum() {
		return this.num;
	}

	public void setNum(Double num) {
		this.num = num;
	}

	@Column(name = "wearhouse", length = 200)
	public String getWearhouse() {
		return this.wearhouse;
	}

	public void setWearhouse(String wearhouse) {
		this.wearhouse = wearhouse;
	}

	@Column(name = "company", nullable = false, length = 100)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "price", precision = 11)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_date", length = 10)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}
	@Transient
	public Double getPriceEnd() {
		return priceEnd;
	}

	public void setPriceEnd(Double priceEnd) {
		this.priceEnd = priceEnd;
	}
	@Transient
	public String getEffectiveDateStr() {
		return effectiveDateStr;
	}

	public void setEffectiveDateStr(String effectiveDateStr) {
		this.effectiveDateStr = effectiveDateStr;
	}
}
