package com.gc.system.entity;

// Generated 2016-6-5 3:46:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ResourceList generated by hbm2java
 */
@Entity
@Table(name = "resource_list")
public class ResourceList implements java.io.Serializable {

	private static final long serialVersionUID = 1938907079602535929L;
	private String id;
	private String company;
	private int uploderUser;
	private String classification;
	private String mainVarieties;
	private String mainSteelfactory;
	private String description;
	private String url;
	private String area;
	private Date uploderTime;

	private User user;
	private String uploderTimeStr;// 检索key

	private String opeRole;// 操作者身份

	public ResourceList() {
	}

	public ResourceList(String id, String company, int uploderUser) {
		this.id = id;
		this.company = company;
		this.uploderUser = uploderUser;
	}

	public ResourceList(String id, String company, int uploderUser,
			String classification, String mainVarieties,
			String mainSteelfactory, String description, String url,
			String area, Date uploderTime) {
		this.id = id;
		this.company = company;
		this.uploderUser = uploderUser;
		this.classification = classification;
		this.mainVarieties = mainVarieties;
		this.mainSteelfactory = mainSteelfactory;
		this.description = description;
		this.url = url;
		this.area = area;
		this.uploderTime = uploderTime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "company", nullable = false, length = 100)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "uploder_user", nullable = false)
	public int getUploderUser() {
		return this.uploderUser;
	}

	public void setUploderUser(int uploderUser) {
		this.uploderUser = uploderUser;
	}

	@Column(name = "classification", length = 200)
	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	@Column(name = "main_varieties", length = 200)
	public String getMainVarieties() {
		return this.mainVarieties;
	}

	public void setMainVarieties(String mainVarieties) {
		this.mainVarieties = mainVarieties;
	}

	@Column(name = "main_steelfactory", length = 200)
	public String getMainSteelfactory() {
		return this.mainSteelfactory;
	}

	public void setMainSteelfactory(String mainSteelfactory) {
		this.mainSteelfactory = mainSteelfactory;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "area", length = 200)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uploder_time", length = 19)
	public Date getUploderTime() {
		return this.uploderTime;
	}

	public void setUploderTime(Date uploderTime) {
		this.uploderTime = uploderTime;
	}

	@Transient
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Transient
	public String getUploderTimeStr() {
		return uploderTimeStr;
	}

	public void setUploderTimeStr(String uploderTimeStr) {
		this.uploderTimeStr = uploderTimeStr;
	}

	@Transient
	public String getOpeRole() {
		return opeRole;
	}

	public void setOpeRole(String opeRole) {
		this.opeRole = opeRole;
	}
}
