package com.gc.system.entity;

// Generated 2016-6-5 3:46:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * StockGoods generated by hbm2java
 */
@Entity
@Table(name = "stock_goods")
public class StockGoods implements java.io.Serializable {

	private Integer id;
	private String resourceListId;
	private String productName;
	private String material;
	private String specifications;
	private String origin;
	private Double price;
	private String wearhouse;

	private Double priceEnd;// 检索条件，非映射字段
	private String area;// 检索条件，非映射字段
	private String company;// 检索条件，非映射字段
	
	private ResourceList resourceList;

	public StockGoods() {
	}

	public StockGoods(String resourceListId, String productName) {
		this.resourceListId = resourceListId;
		this.productName = productName;
	}

	public StockGoods(String resourceListId, String productName,
			String material, String specifications, String origin,
			Double price, String wearhouse) {
		this.resourceListId = resourceListId;
		this.productName = productName;
		this.material = material;
		this.specifications = specifications;
		this.origin = origin;
		this.price = price;
		this.wearhouse = wearhouse;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "resource_list_id", nullable = false, length = 100)
	public String getResourceListId() {
		return this.resourceListId;
	}

	public void setResourceListId(String resourceListId) {
		this.resourceListId = resourceListId;
	}

	@Column(name = "product_name", nullable = false, length = 200)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "material", length = 200)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "specifications", length = 200)
	public String getSpecifications() {
		return this.specifications;
	}

	public void setSpecifications(String specifications) {
		this.specifications = specifications;
	}

	@Column(name = "origin", length = 200)
	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	@Column(name = "price", precision = 11)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "wearhouse", length = 200)
	public String getWearhouse() {
		return this.wearhouse;
	}

	public void setWearhouse(String wearhouse) {
		this.wearhouse = wearhouse;
	}

	@Transient
	public Double getPriceEnd() {
		return priceEnd;
	}

	public void setPriceEnd(Double priceEnd) {
		this.priceEnd = priceEnd;
	}

	@Transient
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Transient
	public ResourceList getResourceList() {
		return resourceList;
	}

	public void setResourceList(ResourceList resourceList) {
		this.resourceList = resourceList;
	}
	@Transient
	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}
}
